GERMANY_STR = "Deutschland"
COUNTRY_STR = "country"
LABEL_STR = "label"
l_outlet_v_PATH = r'C:\Users\SDatta\Palmers\Data\side_data\l_outlet_v.csv'
ALL_RELEVANT_DATA_PATH = r'C:\\Users\\SDatta\\Palmers\\Data\\side_data\\f_sales_v_ba_ro_after_2018.csv'
STORES_LOCATION_PATH = r'C:\Users\Oran Nahum\OneDrive\מסמכים\GitHub\palmers\data\stores_location\store_location_df.csv'
AUSTRIA_REGIONS_BORDER = r'C:\Users\Oran Nahum\OneDrive\מסמכים\GitHub\palmers\data\stores_location\austria_regions_border.json'
GERMANY_REGIONS_BORDER = r'C:\Users\Oran Nahum\OneDrive\מסמכים\GitHub\palmers\data\stores_location\germany_regions_border.json'
AUSTRIA_STR = "Österreich"
OUTLETS_SDATTA = [3, 18, 22, 28, 44, 50, 55, 57, 68, 73, 74, 76, 79, 82, 88, 91, 96, 99, 100, 119, 123, 130, 133, 141, 144, 149, 152, 162, 164, 166, 167, 168, 171, 173, 175, 180, 181, 184, 185, 186, 188, 189, 202, 203, 214, 216, 218, 221, 226, 3005, 3202, 3205, 3208, 3290, 4104, 4123, 4129, 4132, 4133, 4134, 4803, 4805, 4904, 4906]
OUTLETS_PALMERS = [4, 5, 7, 8, 10, 11, 15, 21, 26, 27, 29, 35, 36, 37, 42, 43, 45, 46, 47, 51, 52, 56, 61, 63, 64, 67, 69, 81, 84, 85, 89, 90, 95, 104, 105, 106, 109, 114, 117, 121, 122, 135, 136, 143, 147, 150, 156, 159, 160, 163, 170, 172, 174, 179, 182, 183, 201, 213, 215, 217, 219, 220, 225, 3245]
SALES_STR_YEAR = "2021_sales"
LABEL_COLORS = {-1: 'black', 0: 'red', 1: 'blue', 2: 'yellow', 3: 'green', 4: 'purple', 5: 'orange', 6: 'cyan'}
OWNERSHIP_STR = 'ownership'
SDATTA_STR = 'sdatta'
PALMERS_STR = 'palmers'
divide_size = 1000
lags_array = [0, 1, 2]
AT_REGIONS_NUM = [1,2,3,4,5,6,7,8,9]
DE_REGIONS_STR = ["HH", "BY", "BE", "HB", "HE", "BW", "RP", "SN", "SH", "NI", "BB", "ST", "NW", "MV", "TH", "SL"]
LONGITUDE_STR = "longitude"
LATITUDE_STR = "latitude"
SKU_STR = 'sku'
STORE_STR = 'store'
END_DATE = '2022-01-01'
DATE_STR = 'date'
STORE_ID_STR = "store_id"

DIRECT_LOCATIONS = {'Palmers Lienz Österreich': "Johannespl. 1, 9900 Lienz, Austria",
 'Palmers ECE Kapfenberg Österreich': "8605 Kapfenberg, Austria",
 'Palmers Mauer Österreich': "Geßlgasse 8a, 1230 Wien, Austria",
 'Palmers Kärntnertor Österreich': "Kärntner Str. 53-55, 1010 Wien, Austria",
 'Palmers STEYR Österreich': "Stadtpl. 15, 4400 Steyr, Austria",
 'Palmers Reutte Österreich': "6600 Gemeinde Reutte, Austria",
 'Palmers Vinomacenter Österreich': "6830 Rankweil, Austria",
 'Palmers Bahnhofcity Wien West Österreich': "Europaplatz 1-3 A, 1150 Wien, Austria",
 'Palmers EKZ Riverside Österreich': "Wien, Austria",
 'Palmers Lentia Center Österreich': "Hauptstraße 54, 4040 Linz, Austria",
 'Palmers Alt Erlaa Österreich': "Anton-Baumgartner-Straße 44, 1230 Wien, Austria",
 'Palmers Rotenturm Österreich': "Rotenturmstr. 6, Wien, 1010, Österreich",
 'Palmers Wörgl Österreich': "6300 Wörgl, Austria",
 'Palmers Stadtgalerie Schwaz Österreich': "Andreas Hofer Str. 10, 6130 Schwaz, Austria",
 'Palmers Gleisdorf Österreich': "8200 Gleisdorf, Austria",
 'Palmers Hall Österreich': "6060 Hall in Tirol, Austria",
 'Palmers Ottensheim Österreich': "6060 Hall in Tirol, Austria",
 'Palmers Lech Österreich': "Omesberg 211, 6764 Lech, Austria",
 'Palmers Velden Österreich': "9220 Velden , Austria",
 'Palmers Center West, Shop E73 Österreich': "Hauptpl. 16, 9500 Villach, Austria",
 'Palmers Max Center Österreich': "Gunskirchener Str. 7, 4600 Wels, Austria",
 'Palmers SC Millennium Tower Österreich': "Handelskai 94-96, 1200 Wien, Austria",
 'Palmers Bludenz Österreich': "Werdenbergerstraße 33, 6700 Bludenz, Austria",
 'Palmers Neunkirchen Österreich': "Neunkirchen Österreich",
 'Palmers Mödling Österreich': "Freiheitspl. 8, 2340 Mödling, Austria",
 'Palmers Perchtoldsdorf Österreich': "Wr. G. 2, 2380 Perchtoldsdorf, Austria",
 'Palmers SCS Österreich': "2334 Vösendorf, Austria",
 'Palmers SCA Salzburg Österreich': "5020 Salzburg, Austria",
 'Palmers Huma Österreich': "1110 Wien, Austria",
 'Palmers Q19 Österreich':"Grinzinger Str. 112, 1190 Wien, Austria",
 'Palmers Telfs Österreich': "Weißenbachgasse 9, 6410 Telfs, Austria",
 'Palmers Meidling 23 Österreich': "Meidlinger Hauptstraße 23-25, 1120 Wien, Austria",
 'Palmers Rochus Österreich': "1030 Wien, Austria",
 'Palmers Josefstadt Österreich': "Josefstädter Str. 33, 1080 Wien, Austria",
 'Palmers Nußdorf Österreich': "Nußdorfer Straße 2, 1090 Wien",
 'Palmers Neubau Österreich': "Neubau, Austria",
 'Palmers Kloster Österreich': "Kloster Österreich",
 'Palmers Mirabell Österreich': "Mirabellplatz 8, 5020 Salzburg, Austria",
 'Palmers Hamburg Alstertal Deutschland': "Heegbarg 31, 22391 Hamburg, Germany",
 'Palmers Hamburg Elbe EKZ Deutschland': "Osdorfer Landstraße 125, 22609 Hamburg, Germany",
 'Palmers Hamburg Eppendorf Deutschland': "Eppendorfer Baum 32, 20249 Hamburg, Germany",
 'Palmers Neu-Isenburg Deutschland': "Hermesstraße 4/118, 63263 Neu-Isenburg, Germany",
 'Palmers Frankfurt Kalbächer Ga Deutschland': "Kalbächer G. 12, 60313 Frankfurt am Main, Germany",
 'Palmers Hernals Österreich': "Hernalser Hauptstraße 73, 1170 Wien, Austria",
 'Palmers Reinprecht Österreich': "Reinprechtsdorfer Str. 41, 1050 Wien, Austria",
 'Palmers Stadtplatz Österreich': "Stadtpl. 15, 4400 Steyr, Austria",
 'Palmers Schwarzstraße Österreich': "Schwarzstraße 16, 5020 Salzburg, Austria",
 'Palmers München Sendlinger Deutschland': "Sendlinger Str. 2, 80331 München, Germany",
 'Palmers Regensburg Deutschland': "Donau Einkaufszentrum, Weichser Weg 5, 93059 Regensburg, Germany",
 'Palmers Nürnberg Karolinenstra Deutschland': "Karolinenstraße 28, 90402 Nürnberg, Germany",
 'Palmers Erlangen Arcaden Deutschland': "Nürnberger Str. 1, 91052 Erlangen, Germany",
 'Palmers Ludwigsburg Breuninger Deutschland': "Heinkelstraße 1, 71634 Ludwigsburg, Germany",
 'Palmers Karlsruhe Ettlinger To Deutschland': "Ettlinger-Tor-Platz 1, 76133 Karlsruhe, Germany",
 'Palmers Mozart Österreich': "Getreidegasse 3, 5020 Salzburg, Austria",
 'Palmers Wiener Straße Österreich': "Wiener Straße Österreich",
 'Palmers Ischl Österreich': "4820 Bad Ischl, Austria",
 'Palmers Bregenz Österreich': "Bregenz Österreich",
 'Palmers Feldkirch Österreich': "6800 Feldkirch, Austria",
 'Palmers Oktoberstraße Österreich': "10.-Oktober-Straße 2, 9500 Villach, Austria",
 'Palmers Berlin Kurfürstendamm Deutschland': "Kurfürstendamm 214, 10719 Berlin, Germany",
 'Palmers Berlin Schlossgalerie Deutschland': "Schloßstraße 34, 12163 Berlin, Germany",
 'Palmers Sindelfingen Breuninge Deutschland': "Tilsiter Str. 15, 71065 Sindelfingen, Germany",
 'Palmers Passau Stadtgalerie Deutschland': "Bahnhofstraße 1, 94032 Passau, Germany",
 'Palmers Theresienstraße Österreich': "6020 Innsbruck, Austria",
 'Palmers Kaiser Österreich': "Kaiser Österreich",
 'Palmers Währing Österreich': "Währinger Str. 98, 1180 Wien, Austria",
 'Palmers St.Marx Österreich': "Sankt Marx Österreich",
 'Palmers Tabor Österreich': "Taborstraße 20a, 1020 Wien, Austria",
 'Palmers Schmelz Österreich': "Wr. Str. 2, 8630 Mariazell, Austria",
 'Palmers Dornbirn Österreich': "Dornbirn Austria",
 'Palmers Wieden Österreich': "Wiedner Hauptstraße 39, 1040 Wien, Austria",
 'Palmers Kremsergasse Österreich': "Kremsergasse Österreich",
 'Palmers Brünner Straße Österreich': "Brünner Str. 6-8, 1210 Wien, Austria",
 'Palmers Hietzing Österreich': "Hietzinger Hauptstraße 22, 1130 Wien, Austria",
 'Palmers Quellenstraße Österreich': "Quellenstraße Österreich",
 'Palmers Alser Straße Österreich': "Alser Str. 25, 1080 Wien, Austria",
 'Palmers Kramergasse Österreich': "Kramergasse 6, 9020 Innere Stadt, Austria",
 'Palmers Wassergasse Österreich':"Wassergasse 7, 2500 Baden, Austria",
 'Palmers Baden Casino Österreich': "Kaiser Franz-Ring 1, 2500 Baden, Austria",
 'Palmers SC DEZ Österreich': "Amraser-See-Straße 56a, 6020 Innsbruck, Austria",
 'Palmers Wollzeile Österreich': "Wollzeile 37, 1010 Wien, Austria",
 'Palmers Hauptplatz Österreich': "Hauptpl., 4020 Linz, Austria",
 'Palmers Döbling Österreich': "Döbling, 1190 Vienna, Austria",
 'Palmers SC Donauzentrum 43 Österreich': "Wagramer Str. 94, 1220 Wien, Austria",
 'Palmers Neuer Platz Österreich': "Kramergasse 6, 9020 Innere Stadt, Austria",
 'Palmers Ringstraße Österreich': "Ringstraße, Austria",
 'Palmers SC Interspar Nord Österreich': "Wr. Str. 91, 3500 Krems an der Donau, Austria",
 'Palmers SC Messepark Österreich': "Messestraße 2, 6854 Dornbirn, Austria",
 'Palmers SC Fischapark Österreich': "Ferdinand-Graf-von-Zeppelin-Straße 10, 2700 Wiener Neustadt, Austria",
 'Palmers SC Citypark Österreich': "Lazarettgürtel 55, 8020 Graz, Austria",
 'Palmers Spittal Österreich': "Hauptpl. 3, 9800 Spittal an der Drau, Austria",
 'Palmers SC Plus City Österreich': "Plus-Kauf-Straße 7, 4061 Pasching, Austria",
 'Palmers SC Donauzentrum 176 Österreich': "Wagramer Str. 94, 1220 Wien, Austria",
 'Palmers Leopoldstraße Österreich': "Leopoldstraße Österreich",
 'Palmers City Österreich': "Ares Tower, Donau-City-Straße 11, 1220 Wien, Austria",
 'Palmers SC Traisenpark Österreich': "Dr. Adolf Schärf-Straße 5-9, 3107 St. Pölten, Austria",
 'Palmers SC Nord Österreich': "Ignaz-Köck-Straße 1, 1210 Wien, Austria",
 'Palmers SC Merkur Österreich': "Zwerchäckerweg 20/24, 1220 Wien, Austria",
 'Palmers SC Europark Österreich': "Europastraße 1, 5020 Salzburg, Austria",
 'Palmers Mariahilf 42-46 Österreich': "Mariahilfer Str. 42-46, 1070 Wien, Austria",
 'Palmers SC Südpark Österreich': "2334 Vösendorf, Austria",
 'Palmers SC Auhof Österreich': "Albert-Schweitzer-Gasse 6, 1140 Wien, Austria",
 'Palmers Bruck/Mur Österreich': "Mittergasse 22, 8600 Bruck an der Mur, Austria",
 'Palmers Porzellangasse Österreich': "Porzellangasse 2, 1090 Wien, Austria",
 'Palmers Schuhmeierplatz Österreich': "Schuhmeierpl. 14, 1160 Wien, Austria",
 'Palmers VÖLS Österreich': "EKZ Cyta, 6176 Völs, Austria",
 'Palmers Zimbapark Österreich': "Almteilweg 1, 6706 Bürs, Austria",
 'Palmers SC Seiersberg Österreich': "Shopping City Seiersberg 1/9, 8055 Seiersberg, Austria",
 'Palmers Leoben Österreich': "Hauptpl. 13, 8700 Leoben, Austria",
 'Palmers EKZ-Simmering Österreich': "Simmeringer Hauptstraße 96a, 1110 Wien, Austria",
 'Palmers ECE Klagenfurt Österreich': "Stock, 1020 Wien, Austria",
 'Palmers Atrio Österreich': "Kärntner 34, 9500 Villach, Austria",
 'Palmers FMZ Imst Österreich': "6460 Gemeinde Imst, Austria",
 'Palmers Techgate Österreich': "Donau-City-Straße 9, 1220 Wien, Austria",
 'Palmers Oberwart Österreich': "7400 Oberwart, Austria",
 'Palmers Feldbach Österreich': "Ungarstraße 8, 8330 Feldbach, Austria",
 'Palmers Petersplatz Österreich': "Peterspl. 11, 1010 Wien, Austria",
 'Palmers Stockerau Österreich': "Hauptstr. 38, 2000 Stockerau, Austria",
 'Palmers Graz Center Nord Österreich': "Wiener Str. 351, 8051 Graz, Austria",
 'Palmers WEZ Bärnbach Österreich': "8582 Bärnbach, Austria",
 'Palmers St. Anton Österreich': "6580 St. Anton am Arlberg, Austria",
 'Palmers Enns Österreich': 'Linzer Str. 8, 4470 Enns, Austria',
 'Sillpark Österreich': "6020 Innsbruck, Austria",
 'Getreidegasse Österreich': "5020 Salzburg, Austria",
 'Palmers PADO Österreich': '7111 Parndorf, Austria',
 'Palmers Murpark Österreich': "8041 Graz, Austria",
 'Palmers Liezen Österreich': '8940 Liezen, Austria',
 'Palmers (c/o) Mall of Berlin Deutschland': "Leipziger Pl. 12, 10117 Berlin, Germany" }